service: SlackBot
projectDir: ..
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  runtime: python3.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:PutLogEvents
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - arn:aws:logs:eu-west-1:*:log-group:/aws/lambda/${self:service}-${sls:stage}-Main

functions:
  main:
    name: ${self:service}-${sls:stage}-Main
    timeout: 30
    handler: handlers/main.lambda_handler
    events:
      - http:
          path: /
          method: any
    environment:
      REGION: eu-west-1
      STAGE: ${sls:stage}
      SERVICE_NAME: ${self:service}

package:
  exclude:
    - '**'
  include:
    - ./handlers/**
    - ./config/**
    - ./utils/**

plugins:
  - serverless-pydeps
