service: SlackBot
projectDir: ..
frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  runtime: python3.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:eu-west-1:*:*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:*:*:function:${self:service}-${sls:stage}*"

functions:
  main:
    name: ${self:service}-${sls:stage}-Main
    timeout: 30
    handler: handlers/main.lambda_handler
    events:
      - http:
          path: /
          method: any
    environment:
      REGION: eu-west-1
      STAGE: ${sls:stage}
      SERVICE_NAME: ${self:service}

  asyncProcessor:
    name: ${self:service}-${sls:stage}-AsyncProcessor
    handler: handlers/async_processor.lambda_handler
    timeout: 120
    environment:
      REGION: eu-west-1
      STAGE: ${sls:stage}
      SERVICE_NAME: ${self:service}

package:
  exclude:
    - '**'
  include:
    - ./handlers/**
    - ./config/**
    - ./util/**

plugins:
  - serverless-pydeps
